services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: development
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
  db:
    restart: always
    build:
      context: .
      dockerfile: postgres/Dockerfile
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
